# Generated by Django 2.2.9 on 2020-01-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_crawl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
    ]
