# Generated by Django 2.2.9 on 2020-01-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_crawl', '0002_googledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
