# Generated by Django 2.2.9 on 2020-01-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_crawl', '0004_auto_20200109_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleData',
        ),
    ]
