# Generated by Django 2.2.9 on 2020-01-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_crawl', '0005_delete_googledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='date',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
