# Generated by Django 2.2.9 on 2020-01-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_crawl', '0006_blogdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='tag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
